### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by rkdarst** [scientific-python/yaml2ics#20]
summary: would we like a build system (that makes an index.html) for yaml2ics?  Preview:   https://coderefinery.github.io/calendar/

I've been using yaml2ics as part of something I called "git calendar", which takes a repo of yaml files and complies them to the ics feeds.  This is all pretty standard, and basically what yaml2ics can do already:
https://github.com/coderefinery/git-calendar

The difference is that I made a slightly nice interface, that makes an index.html file for it (still doesn't look too nice, but can be improved).  This is an example of this in use for CodeRefinery:
  https://coderefinery.github.io/calendar/
I previously did this with a Makefile (it was a huge hack), but now has been improved and written in python with a jinja2 template.  It's still not perfect, there are remaining hacks, formatting is bad, I would want to get rid of the legacy Makefile, but it's getting better now.

It's still a bit chaotic, but the essence is one python file:
  https://github.com/coderefinery/git-calendar/blob/main/build.py
+ a simple Github Actions file to build it and the template.  The hardest part is that this embeds yaml2ics as a submodule, and git-calendar itself is embedded as a submodule into the projects that use it.  This has required a lot of manual work when I want to add features that require coordination of yaml2ics and git-calendar.

So, I am wondering, could this functionality be added directly to yaml2ics, then I could deprecate git-calendar.  After yaml2ics becoming install able, it would become a lot easier for me to maintain this and for sub-projects to depend on this and use it (no submodules, instead use venv+pip install).

In practice, I think the #19 (packaging) PR could be altered to make this a package, instead of a module.  And then I would add another module into the package in a separate PR after improving some more.

What do you all think?

**Comment by tupui** [comment]
> So, I am wondering, could this functionality be added directly to yaml2ics, then I could deprecate git-calendar. After yaml2ics becoming install able, it would become a lot easier for me to maintain this and for sub-projects to depend on this and use it (no submodules, instead use venv+pip install).

I am not sure we want to specialise into anything at this stage.

> In practice, I think the #19 (packaging) PR could be altered to make this a package, instead of a module. And then I would add another module into the package in a separate PR after improving some more.

The current PR would already allow to import `yaml2ics`. So you could use all features already available.

**Comment by stefanv** [comment]
As another example, here's our HTML rendering of calendars: https://scientific-python.org/calendars/

I feel this is outside the scope of this project, though.  There's nothing that requires any specialized calendar knowledge in order to build HTML pages.  Jinja, Hugo, or any similar template rendering engine will do the job.
