### ISSUE TITLE
Add the possibility to skip dates for recurring events

### ISSUE THREAD

**Issue by itrich** [scientific-python/yaml2ics#23]
We're an open source community and started today to evaluate this script. Thank you very much for open sourcing this tool!

Is it already planned to skip dates for recurring events (e.g. if one meeting is canceled due to various reasons)?

I've seen that [yaml2ical](https://opendev.org/opendev/yaml2ical/) already provides this feature, but we'd like to stick to this tool.

Thank you in advance,
Eduard

**Comment by stefanv** [comment]
If this feature is supported by icspy, then it should be trivial to add. Do you want to give it a try? I am on family leave right now, so can't look right at this moment, but ping me again in a few weeks if it is not resolved.

**Comment by itrich** [comment]
> If this feature is supported by icspy, then it should be trivial to add. Do you want to give it a try? I am on family leave right now, so can't look right at this moment, but ping me again in a few weeks if it is not resolved. 

Thank you! I've seen that you make use of `dateutil.rrset` as ics-py is still missing the feature of handling recurring events. However, `dateutil.rrset` allows to call [`exdate`](https://dateutil.readthedocs.io/en/stable/rrule.html#rruleset-examples) to remove specific occurences of an event series. I'll give it a shot and hopefully soon open an PR.

**Comment by stefanv** [comment]
That'd be awesome, thanks @itrich!

**Comment by itrich** [comment]
I tried my best, but got struggling with setting the correct timezone to exclude a specific date and time. Any advice or hint is very appreciated! See #24
