### ISSUE TITLE
Define yaml2ics as stable and publish 1.0

### ISSUE THREAD

**Issue by itrich** [scientific-python/yaml2ics#49]
With the latest changes and the pending PR #48, I think `yaml2ics` is in a very good shape. We, the @SovereignCloudStack community use `yaml2ics` to collaboratively maintain our public calendar on a day-to-day basis (see https://github.com/SovereignCloudStack/calendar). It works flawlessly for us, so thanks again for this great piece of tool!

I propose to define `yaml2ics` as stable and publish a major release 1.0.

I'm happy to revise the `README.MD` with a basic usage guide and further information for potential adopters.

What do you think?

**Comment by stefanv** [comment]
I'm glad you find the tool useful! Please go ahead and submit the doc update, then I will tag a release.

**Comment by garloff** [comment]
Unsure if @itrich is able to contribute README.md improvements soon.
In any case, a release would be helpful for our community, as we'd like to start using the `also_on` feature (#45) and that's best be done by referencing a released version of yaml2ics ...
If larger work on README.md is missing, maybe cut a version 0.2 short-term and then target 1.0 in the next months?

**Comment by jarrodmillman** [comment]
@garloff https://pypi.org/project/yaml2ics/0.2/

**Comment by garloff** [comment]
Thanks a lot, really appreciated!

**Comment by stefanv** [comment]
I'd like to get 0.3 out as soon as #51 and #54 are resolved.
